---
wireless_nic_name: wlp58s0
wired_nic_name: enx00051be070f7

peculiar_backports_packages: []
peruliar_stable_packages:
  - firmware-atheros
  - firmware-misc-nonfree

primary_display: eDP-1
external_display: DP-1
