---

- name: Install blueman, feh, mpv, pulseaudio-module-bluetooth on sid
  apt:
    name:
      - blueman
      - feh
      - mpv
      - pulseaudio-dlna
      - pulseaudio-module-bluetooth
    state: latest
    default_release: sid
  become: yes

- name: Config mpv
  copy:
    src: mpv
    dest: "{{ ansible_user_dir }}/.config/"

- name: Install youtube_dl
  pip:
    name: youtube_dl
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest

- name: Copy pulseaudio-dlna.service
  copy:
    src: systemd/user/pulseaudio-dlna.service
    dest: "{{ ansible_user_dir }}/.config/systemd/user/"
