---

- name: Install neovim
  apt:
    name: neovim
    state: latest
    default_release: sid
  become: yes

- name: Config neovim
  copy:
    src: neovim/
    dest: "{{ ansible_user_dir }}/.config/nvim/"

- name: Ensure $HOME/.local/share/nvim/site/autoload folders exists
  file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/"

- name: Install neovim plugins
  shell: nvim +PlugUpdate +qall

- name: Install pynvim
  pip:
    name: pynvim
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest
