---

- name: ensure config folders exists
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  with_items:
    - .config/fontconfig
    - .config/alacritty
    - .config/sway
    - .i3
    - .local/share/fonts

- name: config i3
  copy:
    src: i3.config
    dest: "{{ ansible_user_dir }}/.i3/config"

- name: add lpadmin,systemd-journal groups to user
  user:
    name: "{{ ansible_user_id }}"
    groups: lpadmin,systemd-journal
    append: yes
  become: yes

- name: config alacritty
  copy:
    src: alacritty.yml
    dest: "{{ ansible_user_dir }}/.config/alacritty/"

- name: query x-terminal-emulator
  shell: update-alternatives --query x-terminal-emulator
  register: terminal_emulator
  ignore_errors: yes

- name: install x-terminal-emulator alternatives
  shell: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 10
  when: terminal_emulator|failed
  become: yes

- name: prepare noto color emoji font
  copy:
    src: fonts/NotoColorEmoji.ttf
    dest: "{{ ansible_user_dir }}/.local/share/fonts/"

- name: fonts config
  copy:
    src: fonts/noto_color_emoji.conf
    dest: "{{ ansible_user_dir }}/.config/fontconfig/"

- name: fc-list
  shell: fc-list | grep Emoji
  register: emoji_font
  ignore_errors: yes

- name: fc-cache
  command: fc-cache -fv
  when: emoji_font|failed

- name: config sway
  copy:
    src: sway.config
    dest: "{{ ansible_user_dir }}/.config/sway/config"

- name: start sway
  copy:
    src: start-sway
    dest: "{{ ansible_user_dir }}/.local/bin/"

# For laptop
- block:
  - name: /etc/X11/xorg.conf.d directory exist
    file:
      path: /etc/X11/xorg.conf.d
      state: directory
    become: yes

  - name: config libinput
    copy:
      src: libinput.conf
      dest: /etc/X11/xorg.conf.d/40-libinput.conf
    become: yes
  when: ansible_form_factor == 'Laptop'
