---

- name: config i3
  copy:
    src: i3.config
    dest: "{{ ansible_user_dir }}/.i3/config"

- name: config i3status
  template:
    src: i3status.conf.j2
    dest: "{{ ansible_user_dir }}/.i3status.conf"

- name: add lpadmin group to user for cups
  user:
    name: "{{ ansible_user_id }}"
    groups: lpadmin
    append: yes
  become: yes

- name: config lilyterm
  copy:
    src: lilyterm.conf
    dest: "{{ ansible_user_dir }}/.config/lilyterm/default.conf

# For laptop
- block:
  - name: /etc/X11/xorg.conf.d directory exist
    file:
      path: /etc/X11/xorg.conf.d
      state: directory
    become: yes

  - name: config libinput
    copy:
      src: libinput.conf
      dest: /etc/X11/xorg.conf.d/40-libinput.conf
    become: yes

  - name: config external monitor udev rules
    template:
      src: udev/rules.d/90-monitor-hotplug.rules.j2
      dest: /etc/udev/rules.d/90-monitor-hotplug.rules
    become: yes

  - name: be sure {{ ansible_user_dir }}/.local/bin folder exists
    file:
      path: "{{ ansible_user_dir }}/.local/bin"
      state: directory

  - name: config udev monitor_hotplug programs
    template:
      src: udev/bin/monitor_hotplug.sh.j2
      dest: "{{ ansible_user_dir }}/.local/bin/monitor_hotplug.sh"
      mode: "0755"
  when: ansible_form_factor == 'Laptop'
